import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';

import { QueryProvider } from '@/components/QueryProvider';
import { AuthProvider } from '@/components/SessionProvider';
import { Header } from '@/components/Header';

import { authOptions } from '@/actions/auth';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  // export interface DefaultSession {
  //   user?: {
  //     name?: string | null
  //     email?: string | null
  //     image?: string | null
  //   }
  //   expires: ISODateString
  // }
  const session = await getServerSession(authOptions);
  return (
    <html lang='en' className='dark h-full bg-gray-900'>
      <body className={`${inter.className} h-full`}>
        <AuthProvider session={session}>
          <QueryProvider>
            <Header />
            {children}
            <Toaster expand={true} />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
